---
# CVE Handling Examples
# These examples demonstrate various CVE handling configurations for different use cases

---
# Example 1: Basic CVE Handling with Defaults
# This validator node will automatically scan for CVEs and patch critical vulnerabilities
apiVersion: stellar.org/v1alpha1
kind: StellarNode
metadata:
  name: validator-mainnet-01
  namespace: stellar-nodes
spec:
  nodeType: Validator
  network: Mainnet
  version: "v21.0.0"
  replicas: 1

  # Enable CVE handling with all defaults
  cveHandling:
    enabled: true

  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "16Gi"

  storage:
    storageClass: "ssd"
    size: "500Gi"
    retentionPolicy: Retain

  validatorConfig:
    seedSecretRef: "validator-seed"
    enableHistoryArchive: true

---
# Example 2: Production Validator with Strict CVE Controls
# Conservative settings for mission-critical validator
apiVersion: stellar.org/v1alpha1
kind: StellarNode
metadata:
  name: validator-mainnet-prod
  namespace: stellar-nodes
spec:
  nodeType: Validator
  network: Mainnet
  version: "v21.0.0"
  replicas: 1

  # Strict CVE handling configuration
  cveHandling:
    enabled: true

    # Only patch critical vulnerabilities
    criticalOnly: true

    # Scan less frequently to reduce overhead
    scanIntervalSecs: 7200 # 2 hours

    # Longer timeout for slow networks
    canaryTestTimeoutSecs: 600 # 10 minutes

    # Strict health threshold to catch any issues
    consensusHealthThreshold: 0.98 # 98% health required

    # Enable automatic rollback
    enableAutoRollback: true

  resources:
    requests:
      cpu: "4"
      memory: "16Gi"
    limits:
      cpu: "8"
      memory: "32Gi"

  storage:
    storageClass: "premium-ssd"
    size: "1000Gi"
    retentionPolicy: Retain

  validatorConfig:
    seedSecretRef: "validator-seed"
    enableHistoryArchive: true
    quorumSet: |
      [
        "GCGB2S2KGYARPFA5DAWKJO2QZPWD3BHYZOHBGO46LSZKQVUSIGT3X6T"
      ]

---
# Example 3: Testnet Validator with Aggressive Patching
# Rapid patching to test new security updates
apiVersion: stellar.org/v1alpha1
kind: StellarNode
metadata:
  name: validator-testnet-01
  namespace: stellar-nodes
spec:
  nodeType: Validator
  network: Testnet
  version: "v21.0.0"
  replicas: 1

  # Aggressive CVE handling for testing
  cveHandling:
    enabled: true

    # Patch all vulnerabilities (not just critical)
    criticalOnly: false

    # Scan frequently
    scanIntervalSecs: 1800 # 30 minutes

    # Shorter canary timeout for faster iteration
    canaryTestTimeoutSecs: 180 # 3 minutes

    # Less strict health requirements for test environment
    consensusHealthThreshold: 0.90

    # Enable automatic rollback
    enableAutoRollback: true

  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "16Gi"

  storage:
    storageClass: "standard"
    size: "250Gi"
    retentionPolicy: Delete

  validatorConfig:
    seedSecretRef: "testnet-validator-seed"
    enableHistoryArchive: false

---
# Example 4: Horizon API Server with CVE Handling
# API server with automatic patching
apiVersion: stellar.org/v1alpha1
kind: StellarNode
metadata:
  name: horizon-prod-01
  namespace: stellar-nodes
spec:
  nodeType: Horizon
  network: Mainnet
  version: "v21.0.0"
  replicas: 3

  # CVE handling for Horizon
  cveHandling:
    enabled: true
    scanIntervalSecs: 3600
    canaryTestTimeoutSecs: 300
    enableAutoRollback: true
    consensusHealthThreshold: 0.95

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  storage:
    storageClass: "ssd"
    size: "100Gi"
    retentionPolicy: Retain

  horizonConfig:
    databaseSecretRef: "horizon-db-secret"
    stellarCoreUrl: "http://core.default:11626"

  # Auto-scaling for API traffic
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilization: 70
    targetMemoryUtilization: 80

  # Expose via ingress
  ingress:
    enabled: true
    ingressClassName: "nginx"
    host: "horizon.example.com"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"

---
# Example 5: CVE Handling Disabled (Manual Patching)
# Node where you want to manually control patching
apiVersion: stellar.org/v1alpha1
kind: StellarNode
metadata:
  name: validator-manual-patch
  namespace: stellar-nodes
spec:
  nodeType: Validator
  network: Testnet
  version: "v21.0.0"
  replicas: 1

  # Disable automatic CVE handling
  # Patches will be applied by updating the version field manually
  cveHandling:
    enabled: false

  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "16Gi"

  storage:
    storageClass: "standard"
    size: "500Gi"
    retentionPolicy: Retain

  validatorConfig:
    seedSecretRef: "validator-seed"

---
# Example 6: Multiple Nodes with Different CVE Policies
# Combined manifest for a multi-node setup
---
apiVersion: stellar.org/v1alpha1
kind: StellarNode
metadata:
  name: validator-primary
  namespace: stellar-nodes
  labels:
    tier: primary
spec:
  nodeType: Validator
  network: Mainnet
  version: "v21.0.0"
  replicas: 1

  # Strict CVE handling for primary node
  cveHandling:
    enabled: true
    criticalOnly: true
    scanIntervalSecs: 7200
    consensusHealthThreshold: 0.98
    enableAutoRollback: true

  resources:
    requests:
      cpu: "4"
      memory: "16Gi"
    limits:
      cpu: "8"
      memory: "32Gi"

  storage:
    storageClass: "premium-ssd"
    size: "1000Gi"

  validatorConfig:
    seedSecretRef: "primary-seed"

---
apiVersion: stellar.org/v1alpha1
kind: StellarNode
metadata:
  name: validator-backup
  namespace: stellar-nodes
  labels:
    tier: backup
spec:
  nodeType: Validator
  network: Mainnet
  version: "v21.0.0"
  replicas: 1

  # More aggressive CVE handling for backup node (test patches first)
  cveHandling:
    enabled: true
    criticalOnly: false
    scanIntervalSecs: 3600
    consensusHealthThreshold: 0.90
    enableAutoRollback: true

  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "16Gi"

  storage:
    storageClass: "ssd"
    size: "500Gi"

  validatorConfig:
    seedSecretRef: "backup-seed"

---
# Example 7: Soroban RPC with CVE Handling
apiVersion: stellar.org/v1alpha1
kind: StellarNode
metadata:
  name: soroban-rpc-prod
  namespace: stellar-nodes
spec:
  nodeType: SorobanRpc
  network: Mainnet
  version: "v21.0.0"
  replicas: 2

  # CVE handling for Soroban RPC
  cveHandling:
    enabled: true
    scanIntervalSecs: 3600
    canaryTestTimeoutSecs: 300
    enableAutoRollback: true
    consensusHealthThreshold: 0.95

  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "8Gi"

  storage:
    storageClass: "ssd"
    size: "50Gi"

  sorobanConfig:
    stellarCoreUrl: "http://core.default:11626"

  # Expose Soroban RPC
  ingress:
    enabled: true
    ingressClassName: "nginx"
    host: "soroban-rpc.example.com"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
